<?php  

$paymentMethod = $this->getRow();
$attributes = $this->getAttributes();


?>

<form action="<?php echo $this->getUrl('save','paymentmethod'); ?>" method="POST">
	<div class="d-flex align-items-center justify-content-sm-between">
		<p class="fw-bolder fs-4">Edit Payment method</p>
			<button class="btn btn-dark ms-5">Save</button>
			<div class="m-2 mx-2"><a class="btn btn-dark pull-right" href="<?php echo $this->getUrl('grid','paymentmethod', [], true);?>">cancel</a></div>
		</div>
	<table class="table table-striped">
		<tr>
			<td>
				<label>name</label>
			</td>
			<td>
				<input type="text" name="paymentmethod[name]" value="<?php echo $paymentMethod->name; ?>">
				<input type="hidden" name="updated_at" value=""required>
			</td>
		</tr>
		<tr>
			<td>
				<label>status</label>
			</td>
			<td>
				<select name="paymentmethod[status]" >
				<?php foreach($paymentMethod->getResource()->getStatusOptions() as $key => $value): ?>
				<?php $selected = ($key == $paymentMethod->getStatus()) ? 'selected' : ''; ?>
				<option value="<?php echo $key; ?>" <?php echo $selected ;?>> <?php echo $value;?>
				 </option>
				<?php endforeach; ?>
			</select>
			</td>
		</tr>
		<?php foreach($attributes as $key => $attribute): ?>
		<tr>
			<td><?php echo $attribute->name ;?></td>
			<td>
				<?php $this->getLayout()->createBlock('Core_Eav_Attribute_InputType')->setAttribute($attribute)->setRow($paymentMethod)->render(); ?>
			</td>
		</tr>
	<?php endforeach; ?>
	</table>
