<?php  
$paymentMethods = $this->getPaymentMethods();
?>
<div class="d-flex align-items-center justify-content-sm-between">
	<p class="fw-bolder fs-4">Manage Payment method</p>
	
		<div class="m-2 mx-2"><a class="btn btn-dark pull-right" href="<?php echo $this->getUrl('add','paymentmethod'); ?>">Add paymentmethod</a></div>
	
</div>
<table class="table table-striped text-center ">
		<tr>
			<th>payment_method_id</th>
			<th>name</th>
			<th>status</th>
			<th>created_at</th>
			<th>updated_at</th>
			<th>edit</th>
			<th>delete</th>
		</tr>
		<?php foreach($paymentMethods->getData() as $paymentMethod):?>
			<tr>
				<td><?php echo $paymentMethod->payment_method_id; ?></td>
				<td><?php echo $paymentMethod->name; ?></td>
				<td><?php echo $paymentMethod->getStatusText($paymentMethod->status); ?></td>
				<td><?php echo $paymentMethod->created_at; ?></td>
				<td><?php echo $paymentMethod->updated_at; ?></td>

				<td><a href="<?php echo $this->getUrl('edit','paymentmethod', ['payment_method_id' => $paymentMethod->payment_method_id]); ?>">edit</a></td>
				<td><a href="<?php echo $this->getUrl('delete','paymentmethod', ['payment_method_id' => $paymentMethod->payment_method_id]); ?>">delete</a></td>
			</tr>
		<?php endforeach; ?>
	</table>
</body>
</html>