<?php 
$items = $this->getItems();
?>
<div class="d-flex align-items-center justify-content-sm-between">
	<p class="fw-bolder fs-4">Manage item</p>
	
		<div class="m-2 mx-2"><a class="btn btn-dark pull-right" href="<?php echo $this->getUrl('add','item'); ?>">Add Item</a></div>
	
</div>
<table class="table table-striped text-center ">
	<tr>
		<th>entity_id</th>
		<th>SKU</th>
        <th>Status</th>
        <th>Created_at</th>
        <th>Updated_at</th>
        <th>Edit</th>
        <th>Delete</th>
	</tr>

	<?php if (!$items):?>
		<tr>
			<td colspan="16">No record found</td>
		</tr>
	<?php else: ?>

	<?php foreach ($items->getData() as $item):?>
		<tr>
			<td><?php echo $item->entity_id ; ?></td>
			<td><?php echo $item->SKU; ?></td>
			<td><?php echo $item->status; ?></td>
			<td><?php echo $item->created_at; ?></td>
			<td><?php echo $item->updated_at; ?></td>

			<td><a href="<?php echo $this->getUrl('edit', 'item', ['entity_id' => $item->entity_id]); ?>">Edit</a></td>
			<td><a href="<?php echo $this->getUrl('delete', 'item', ['entity_id' => $item->entity_id]); ?>">Delete</a></td>
	    </tr>
		<?php endforeach; ?>
	<?php endif;?>


</table>
