<nav class="navbar bg-white" data-bs-theme="dark">
	<div class="container-fluid">
			<a class="btn btn-primary" href="index.php?c=product&a=grid">Product</a>
			<a class="btn btn-primary" href="index.php?c=category&a=grid">Category</a>
			<a class="btn btn-primary" href="index.php?c=customer&a=grid">Customer</a>
			<a class="btn btn-primary" href="index.php?c=salesman&a=grid">Salesman</a>
			<a class="btn btn-primary" href="index.php?c=vendor&a=grid">Vendor</a>
			<a class="btn btn-primary" href="index.php?c=shippingmethod&a=grid">ShippingMethod</a>
			<a class="btn btn-primary" href="index.php?c=paymentmethod&a=grid">PaymentMethod</a>
			<a class="btn btn-primary" href="index.php?c=admin&a=grid">Admin</a>
			<a class="btn btn-primary" href="index.php?c=eav_attribute&a=grid">Eav Attribute</a>
			<a class="btn btn-primary" href="index.php?c=item&a=grid">Item</a>
	</div>
</nav>





