<nav class="navbar bg-white" data-bs-theme="dark">
	<div class="container-fluid">
			<a class="btn btn-primary" href="index.php?c=product&a=index">Product</a>
			<a class="btn btn-primary" href="index.php?c=category&a=index">Category</a>
			<a class="btn btn-primary" href="index.php?c=customer&a=index">Customer</a>
			<a class="btn btn-primary" href="index.php?c=salesman&a=index">Salesman</a>
			<a class="btn btn-primary" href="index.php?c=vendor&a=index">Vendor</a>
			<a class="btn btn-primary" href="index.php?c=shippingmethod&a=index">ShippingMethod</a>
			<a class="btn btn-primary" href="index.php?c=paymentmethod&a=index">PaymentMethod</a>
			<a class="btn btn-primary" href="index.php?c=admin&a=index">Admin</a>
			<a class="btn btn-primary" href="index.php?c=eav_attribute&a=index">Eav Attribute</a>
			<a class="btn btn-primary" href="index.php?c=item&a=index">Item</a>
	</div>
</nav>





