<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<script type="text/javascript" src="Skin/js/jquery-3.6.4.min.js"></script>
<script type="text/javascript" src="Skin/js/ajax.js"></script>

<?php foreach($this->getAllJs() as $src): ?>
<script type="text/javascript" src="<?php echo $src; ?>"></script>
<?php endforeach; ?>

<title><?php echo $this->getTitle();  ?></title>
</head>
