<?php 
$products = $this->getProducts();
?>
<div class="d-flex align-items-center justify-content-sm-between">
	<p class="fw-bolder fs-4">Manage Product</p>
	
		<div class="m-2 mx-2"><a class="btn btn-dark pull-right" href="<?php echo $this->getUrl('add','product'); ?>">Add Product</a></div>
	
</div>
<table class="table table-striped text-center ">
	<tr>
		<th>Product_id</th>
		<th>Name</th>
		<th>SKU</th>
		<th>Cost</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Description</th>
        <th>Status</th>
        <th>Color</th>
        <th>Material</th>
        <th>Created_at</th>
        <th>Updated_at</th>
        <th>Media</th>
        <th>Edit</th>
        <th>Delete</th>
	</tr>

	<?php if (!$products):?>
		<tr>
			<td colspan="16">No record found</td>
		</tr>
	<?php else: ?>

	<?php foreach ($products->getData() as $product):?>
		<tr>
			<td><?php echo $product->product_id; ?></td>
			<td><?php echo $product->name; ?></td>
			<td><?php echo $product->SKU; ?></td>
			<td><?php echo $product->cost; ?></td>
			<td><?php echo $product->price; ?></td>
			<td><?php echo $product->quantity; ?></td>
			<td><?php echo $product->description; ?></td>
			<td><?php echo $product->getStatusText($product->status); ?></td>
			<td><?php echo $product->color; ?></td>
			<td><?php echo $product->material; ?></td>
			<td><?php echo $product->created_at; ?></td>
			<td><?php echo $product->updated_at; ?></td>

			<td><a href="<?php echo $this->getUrl('grid', 'product_media', ['product_id' => $product->product_id]); ?>">Media</a></td>
			<td><a href="<?php echo $this->getUrl('edit', 'product', ['product_id' => $product->product_id]); ?>">Edit</a></td>
			<td><a href="<?php echo $this->getUrl('delete', 'product', ['product_id' => $product->product_id]); ?>">Delete</a></td>
	    </tr>
		<?php endforeach; ?>
	<?php endif;?>


</table>
