<?php
$attribute = $this->getAttribute();
$attributeOptions = $this->getAttributeOption();


// echo "<pre>";
// print_r($attributeOptions);

?>
<form action="<?php echo $this->getUrl('save', 'eav_attribute', ['attribute_id' => $attribute->getId()]) ?>" method="post">
	<div class="d-flex align-items-center justify-content-sm-between">
		<p class="fw-bolder fs-4">Edit Attributes</p>
			<button class="btn btn-dark ms-5">Save</button>
			<div class="m-2 mx-2"><a class="btn btn-dark pull-right" href="<?php echo $this->getUrl('grid','eav_attribute', [], true);?>">cancel</a></div>
		</div>
<table class="table table-striped">
	<thead>
        <tr>
            <td>entity_type</td>
            <td>
                <select name="attribute[entity_type_id]">
                    <?php# foreach ($attribute->getEntityType() as $key => $value): ?>
                    <option value="<?php #echo $key  ?>"><?php# echo $value ?></option>
                    <?php# endforeach; ?>                 
                </select>
            </td>
            <td></td>
        </tr>
		<tr>
			<td>Code</td>
			<td>
				<input type="text" name="attribute[code]" value="<?php echo $attribute->code; ?>" required>
			</td>
            <td></td>
		</tr>
		<tr>
			<td>backend type</td>
			<td>
				<select name="attribute[backend_type]" >
                    <option value="integer">Integer</option>
                    <option value="varchar">Varchar</option>
                    <option value="decimal">Decimal</option>
                    <option value="datetime">Date and Time</option>
                    <option value="text">Text</option>
                </select>
			</td>
            <td></td>
		</tr>
        <tr>
            <td>input_type</td>
            <td>
                <select id="inputTypeSelect" name="attribute[input_type]" onchange="changeInputType(this)">
                    <option value="textBox">Text Box</option>
                    <option value="textArea">Text Area</option>
                    <option value="select">Select</option>
                    <option value="multiSelect">Multi Select</option>
                    <option value="radio">Radio</option>
                    <option value="checkBox">Check Box</option>
                </select>
            </td>
            <td>
                <div id="inputTypeOptionDiv">
                    <table>
                        <thead>
                            <tr>
                                <th>Option Name</th>
                                <th>position</th>
                                <th><input type="button" name="add" value="ADD" id="addOption" /></th>
                            </tr>
                        </thead>
                        <tbody id="inputTypeOptionTable">
                            <tbody id="inputTypeOptionTable">
                            <?php foreach($attributeOptions as $attributeOption) : ?>
                            <tr>
                                <td><input type="text" name="option[exist][<?php echo $attributeOption->option_id; ?>]" value="<?php echo $attributeOption->name; ?>"/></td>
                                <td><input type="text" name="position[exist][<?php echo $attributeOption->option_id; ?>]" value="<?php echo $attributeOption->position; ?>"/></td>
                                <td><input type="button" name="remove" value="REMOVE 1" class="removeOption" ></td>
                            </tr>
                            <?php endforeach; ?>
                             </tbody>
                        </tbody>
                    </table>
                </div>
            </td>
        </tr>
        <tr>
            <td>name</td>
            <td>
                <input type="text" name="attribute[name]" value="<?php echo $attribute->name; ?>" required>
            </td>
            <td></td>
        </tr>
        <tr>
            <td>status</td>
            <td>
                <select name="attribute[status]">
                    <?php foreach($attribute->getResource()->getStatusOptions() as $key => $value): ?>
                    <?php $selected = ($key == $attribute->getStatus()) ? 'selected' : ''; ?>
                    <option value="<?php echo $key; ?>" <?php echo $selected; ?>> <?php echo $value; ?> </option>
                    <?php endforeach; ?>
                </select>
            </td>
            <td></td>
        </tr>
        <tr>
            <td>backend_model</td>
            <td>
                <input type="text" name="attribute[backend_model]" value="<?php echo $attribute->backend_model; ?>">
            </td>
            <td></td>
        </tr>
	</thead>
</table>
</form>
</div>
<table style="display: none;">
    <tbody id="inputTypeOptionDefault">
        <tr>
            <td><input type="text" name="option[new][]" /></td>
            <td><input type="text" name="position[new][]" /></td>
            <td><input type="button" name="remove" value="REMOVE" class="removeOption" ></td>
        </tr>
    </tbody>
</table>
<script type="text/javascript">

$('.removeOption').click(function () {
    console.log($(this).parent().parent().remove());
});

$('#addOption').click(function () {
    $('#inputTypeOptionTable').prepend($('#inputTypeOptionDefault').html());
});

$('#inputTypeSelect').change(function () {
    var inputType = $(this);
    if (inputType.val() == 'select' || inputType.val() == 'multiSelect' || inputType.val() == 'radio' || inputType.val() == 'checkBox') {
        $('#inputTypeOptionDiv').show();
    }
    else{
        $('#inputTypeOptionDiv').hide();
    }
});

$(document).ready(function () {
    $('#inputTypeSelect').trigger('change');

});

</script>