<?php $admins = $this->getAdmins()->getData(); ?>

<div class="d-flex align-items-center justify-content-sm-between">
	<p class="fw-bolder fs-4">Manage Admin</p>
	<div class="m-2 mx-2"><a class="btn btn-dark pull-right" href="<?php echo $this->getUrl('add','admin'); ?>">Add Admin</a></div>
</div>
<table class="table table-striped text-center ">
	<tr>
		<td>Admin_id</td>
		<td>Email</td>
		<td>status</td>
		<td>created_at</td>
		<td>updated_at</td>
		<td>Edit</td>
		<td>Delete</td>
	</tr>

	<?php if (!$admins):?>
	<tr>
		<td colspan="5">No record available.</td>
	</tr>
	<?php else: ?>
		<?php foreach($admins as $admin): ?>
		<tr>
			<td><?php echo $admin->admin_id; ?></td>
			<td><?php echo $admin->email; ?></td>
			<td><?php echo $admin->getStatusText(); ?></td>
			<td><?php echo $admin->created_at; ?></td>
			<td><?php echo $admin->updated_at; ?></td>
			<td><a href="<?php echo $this->getUrl('edit', null, ['id' => $admin->admin_id])?>">Edit</a></td>
			<td><a href="<?php echo $this->getUrl('delete', null,  ['id' => $admin->admin_id]); ?>">Delete</a></td>
		</tr>	
		<?php endforeach; ?>
	<?php endif; ?>

</table>
