<?php $attribute = $this->getAttribute(); ?>
<?php $options = $attribute->getOption(); #echo "<pre>"; print_r($options->getData()); ?>
<?php $row = $this->getRow(); #echo "<pre>"; print_r($row); ?>

<select name="attribute[<?php echo $attribute->backend_type ?>][<?php echo $attribute->getId();?>]">
    <option value="0">select</option>
    <?php if($options): ?>
        <?php foreach ($options->getData() as $option):?>
            <?php $selected = ($row->getAttributeValue($attribute) == $option->option_id)? 'selected' : '' ?>
            <option value="<?php echo $option->option_id ?>" <?php echo $selected ?>><?php echo $option->name; ?></option>
        <?php endforeach; ?>
    <?php endif; ?>
</select>