<?php 
$attributes = $this->getAttributes()->getData();
?>
<div class="d-flex align-items-center justify-content-sm-between">
	<p class="fw-bolder fs-4">Manage Attribute</p>
	
	<div class="m-2 mx-2"><a class="btn btn-dark pull-right" href="<?php echo $this->getUrl('add','eav_attribute'); ?>">Add Attribute</a></div>
	
</div>
<table class="table table-striped text-center ">
	<tr>
		<th>attribute_id</th>
		<th>entity_type_id</th>
		<th>code</th>
		<th>backend_type</th>
        <th>name</th>
        <th>status</th>
        <th>backend_model</th>
        <th>input_type</th>
        <th>Edit</th>
        <th>Delete</th>
	</tr>

	<?php if (!$attributes):?>
		<tr>
			<td colspan="16">No record found</td>
		</tr>
	<?php else: ?>

	<?php foreach ($attributes as $attribute):?>
		<tr>
			<td><?php echo $attribute->attribute_id; ?></td>
			<td><?php echo $attribute->entity_type_id; ?></td>
			<td><?php echo $attribute->code; ?></td>
			<td><?php echo $attribute->backend_type; ?></td>
			<td><?php echo $attribute->name; ?></td>
			<td><?php echo $attribute->getStatusText($attribute->status); ?></td>
			<td><?php echo $attribute->backend_model; ?></td>
			<td><?php echo $attribute->input_type; ?></td>

			<td><a href="<?php echo $this->getUrl('edit', 'eav_attribute', ['attribute_id' => $attribute->attribute_id]); ?>">Edit</a></td>
			<td><a href="<?php echo $this->getUrl('delete', 'eav_attribute', ['attribute_id' => $attribute->product_id]); ?>">Delete</a></td>
	    </tr>
		<?php endforeach; ?>
	<?php endif;?>


</table>
