<!DOCTYPE html>
<html>
<?php $this->createBlock('Head')->render(); ?>
<body>
	<table width="100%" border="1px solid bLack" style="text">
		<tr height="100">
			<td colspan="3">Header</td>
		</tr>
		<tr height="40">
			<td colspan="3">Message</td>	
		</tr>
		<tr height="250">
			<td>Left</td>
			<td>content</td>
		</tr>
		<tr height="50">
			<td colspan="3">Footer</td>
		</tr>
	</table>
</body>
</html>