<!DOCTYPE html>
<html>
<?php echo $this->getChildHtml('head'); ?>
<body>
	<table class="w-100">
		<tr style=" height:100px">
			<td colspan="3"><?php echo $this->getChildHtml('header'); ?></td>
		</tr>
		<tr style=" height:35px">
			<td colspan="3" id="message-html"><?php echo $this->getChildHtml('message'); ?></td>
		</tr>
		<tr style="height: 300px;">
			<td width="10%"></td>
			<td><?php echo $this->getChildHtml('content'); ?></td>
			<td width="10%"></td>
		</tr>
		<tr style="height: 100px;">
			<td colspan="3"><?php echo $this->getChildHtml('footer'); ?></td>
		</tr>
	</table>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>