<?php  
$final = $this->getCustomer();
$customer = $final[0];

$billingAddress = $this->getBillingAddress();
$shippingAddress = $this->getShippingAddress();

?>
<form action="<?php echo $this->getUrl('save','customer', ['customer_id' => $customer->getId()]);?>" method="post">
<div class="d-flex align-items-center justify-content-sm-between">
		<p class="fw-bolder fs-4">Edit Customer</p>
			<button class="btn btn-dark ms-5">Save</button>
			<div class="m-2 mx-2"><a class="btn btn-dark pull-right" href="<?php echo $this->getUrl('grid','customer', [], true);?>">cancel</a></div>
		</div>
<table class="table table-striped">
	<tr>
		<td>
			<label>first_name</label>
		</td>
		<td>
			<input type="text" name="customer[first_name]" value="<?php echo $customer->first_name ?>">
			<input type="hidden" name="updated_at" value=""required>
		</td>
	</tr>
	<tr>
		<td>
			<label>last_name</label>
		</td>
		<td>
			<input type="text" name="customer[last_name]" value="<?php echo $customer->last_name ?>">
		</td>
	</tr>
	<tr>
		<td>
			<label>email</label>
		</td>
		<td>
			<input type="text" name="customer[email]" value="<?php echo $customer->email ?>">
		</td>
	</tr>
	<tr>
		<td>
			<label>gender</label>
		</td>
		<td>
			<select name="customer[gender]" >
				<option value="male" <?php if ($customer->gender === 'male'){
													echo "selected";}
												?>>male</option>
					
				<option value="female" <?php if ($customer->gender === 'female'){
													echo "selected";}
												?>>female</option>
			</select>
		</td>
	</tr>
	<tr>
		<td>
			<label>mobile</label>
		</td>
		<td>
			<input type="text" name="customer[mobile]" value="<?php echo $customer->mobile ?>">
		</td>
	</tr>
	<tr>
		<td>
			<label>status</label>
		</td>
		<td>
			<select name="customer[status]" >
				<?php foreach($customer->getResource()->getStatusOptions() as $key => $value): ?>
				<?php $selected = ($key == $customer->getStatus()) ? 'selected' : ''; ?>
				<option value="<?php echo $key; ?>" <?php echo $selected ;?>> <?php echo $value;?>
				 </option>
				<?php endforeach; ?>
			</select>
		</td>
	</tr>
</table>	
<br>
<p class="fw-bolder fs-4">Edit Billing Address</p>
<table class="table table-striped">
	<tr>
		<td>
			<label>address</label>
		</td>
		<td>
			<input type="text" name="billingAddress[address]" value="<?php echo $billingAddress->address;?>">
		</td>
	</tr>
	<tr>
		<td>shippingAddress
			<label>city</label>
		</td>
		<td>
			<input type="text" name="billingAddress[city]" value="<?php echo $billingAddress->city; ?>">
		</td>
	</tr>
	<tr>
		<td>
			<label>state</label>
		</td>
		<td>
			<input type="text" name="billingAddress[state]" value="<?php echo $billingAddress->state; ?>">
		</td>
	</tr>
	<tr>
		<td>
			<label>country</label>
		</td>
		<td>
			<input type="text" name="billingAddress[country]" value="<?php echo $billingAddress->country; ?>">
		</td>
	</tr>
   	<tr>
		<td>
			<label>zipcode</label>
		</td>
		<td>
			<input type="text" name="billingAddress[zipcode]" value="<?php echo $billingAddress->zipcode; ?>">
		</td>
	</tr>
</table>
<p class="fw-bolder fs-4">Edit Shipping Address</p>
<table class="table table-striped">
	<tr>
		<td>
			<label>address</label>
		</td>
		<td>
			<input type="text" name="shippingAddress[address]" value="<?php echo $shippingAddress->address;?>">
		</td>
	</tr>
	<tr>
		<td>
			<label>city</label>
		</td>
		<td>
			<input type="text" name="shippingAddress[city]" value="<?php echo $shippingAddress->city; ?>">
		</td>
	</tr>
	<tr>
		<td>
			<label>state</label>
		</td>
		<td>
			<input type="text" name="shippingAddress[state]" value="<?php echo $shippingAddress->state; ?>">
		</td>
	</tr>
	<tr>
		<td>
			<label>country</label>
		</td>
		<td>
			<input type="text" name="shippingAddress[country]" value="<?php echo $shippingAddress->country; ?>">
		</tdshippingAddress	</tr>
   	<tr>
		<td>
			<label>zipcode</label>
		</td>
		<td>
			<input type="text" name="shippingAddress[zipcode]" value="<?php echo $shippingAddress->zipcode; ?>">
		</td>
	</tr>




</table>
</form>
