<?php  

$categories = $this->getCategories();

?>
<div class="d-flex align-items-center justify-content-sm-between">
	<p class="fw-bolder fs-4">Manage Category</p>
	<div class="m-2 mx-2"><a class="btn btn-dark pull-right" href="<?php echo $this->getUrl('add','category'); ?>">Add Category</a></div>
</div>
<table class="table table-striped text-center ">
		<tr>
			<th>category_id</th>
			<th>name</th>
			<th>status</th>
			<th>description</th>
			<th>created_at</th>
			<th>updated_at</th>
			<th>edit</th>
			<th>delete</th>
		</tr>

		<?php if (!$categories):?>

		<tr>
			<td colspan="16">No record found</td>
		</tr>
		<?php else: ?>

	    <?php foreach($categories->getData() as $category): ?>
		<tr>
			<td><?php echo $category->category_id;?></td>
			<td><?php echo $category->getPathCategories($category->category_id);?></td>
			<td><?php echo $category->getStatusText($category->status); ?></td>
			<td><?php echo $category->description;?></td>
			<td><?php echo $category->created_at;?></td>
			<td><?php echo $category->updated_at;?></td>

			<td><a href="<?php echo $this->getUrl('edit','category',['category_id' => $category->category_id]);?>">Edit</a></td>
			<td><a href="<?php echo $this->getUrl('delete','category',['category_id' => $category->category_id]);?>">delete</a></td>
		</tr>
	<?php endforeach;?>
	<?php endif;?>

	</table>
