<?php  
$final = $this->getSalesman();
$salesman = $final[0];
$address = $final[1];
?>

<form action="<?php echo $this->getUrl('save','salesman',['salesman_id' => $salesman->getId()]); ?>" method ="POST" id="salesman-form">
<div class="d-flex align-items-center justify-content-sm-between">
		<p class="fw-bolder fs-4">Edit Salesman</p>
			<button class="btn btn-dark ms-5" type="button" onclick="ajax.setUrl('<?php echo $this->getUrl('save') ?>').setForm('salesman-form').call();">Save</button>
			<button class="btn btn-dark ms-5" type="button" onclick="ajax.setUrl('<?php echo $this->getUrl('grid','',[],true) ?>').call();">Cancel</button>
		</div>
<table class="table table-striped">
		<tr>
			<td>
				<label>first_name</label>
			</td>
			<td>
				<input type="text" name="salesman[first_name]" value="<?php echo $salesman->first_name;?>">
				<input type="hidden" name="updated_at" value="" required>
			</td>
		</tr>
		<tr>
			<td>
				<label>last_name</label>
			</td>
			<td>
				<input type="text" name="salesman[last_name]" value="<?php echo $salesman->last_name;?>">
			</td>
		</tr>
		<tr>
			<td>
				<label>email</label>
			</td>
			<td>
				<input type="email" name="salesman[email]" value="<?php echo $salesman->email;?>">
			</td>
		</tr>
		<tr>
			<td>
				<label>gender</label>
			</td>
			<td>
				<select name="salesman[gender]" >
				<option value="male" <?php if ($salesman->gender === 'male'){
													echo "selected";}
												?>>male</option>
					
				<option value="female" <?php if ($salesman->gender === 'female'){
													echo "selected";}
												?>>female</option>
			</select>
			</td>
		</tr>
		<tr>
			<td>
				<label>mobile</label>
			</td>
			<td>
				<input type="text" name="salesman[mobile]" value="<?php echo $salesman->mobile;?>">
			</td>
		</tr>
		<tr>
			<td>
				<label>status</label>
			</td>
			<td>
				<select name="salesman[status]" >
				<?php foreach($salesman->getResource()->getStatusOptions() as $key => $value): ?>
				<?php $selected = ($key == $salesman->getStatus()) ? 'selected' : ''; ?>
				<option value="<?php echo $key; ?>" <?php echo $selected ;?>> <?php echo $value;?>
				 </option>
				<?php endforeach; ?>
			</select>	
			</td>
		</tr>
		<tr>
			<td>
				<label>company</label>
			</td>
			<td>
				<input type="text" name="salesman[company]" value="<?php echo $salesman->company;?>">
			</td>
		</tr>
	</table>
	<p class="fw-bolder fs-4">Edit Address</p>
	<table class="table table-striped">
		<tr>
			<td>
				<label>address</label>
			</td>
			<td>
				<input type="text" name="address[address]" value="<?php echo $address->address;?>">
			</td>
		</tr>
		<tr>
			<td>
				<label>city</label>
			</td>
			<td>
				<input type="text" name="address[city]" value="<?php echo $address->city;?>">
			</td>
		</tr>
		<tr>
			<td>
				<label>state</label>
			</td>
			<td>
				<input type="text" name="address[state]" value="<?php echo $address->state;?>">
			</td>
		</tr>
		<tr>
			<td>
				<label>country</label>
			</td>
			<td>
				<input type="text" name="address[country]" value="<?php echo $address->country;?>">
			</td>
		</tr>
		<tr>
			<td>
				<label>zipcode</label>
			</td>
			<td>
				<input type="text" name="address[zipcode]" value="<?php echo $address->zipcode;?>">
			</td>
		</tr>
	</table>
</form>
