<?php  

$shippingMethod = $this->getShippingMethod();


?>
<form action="<?php echo $this->getUrl('save','shippingmethod')?>" method="post">
<div class="d-flex align-items-center justify-content-sm-between">
		<p class="fw-bolder fs-4">Edit Shippingmethod</p>
			<button class="btn btn-dark ms-5">Save</button>
			<div class="m-2 mx-2"><a class="btn btn-dark pull-right" href="<?php echo $this->getUrl('grid','shippingmethod', [], true);?>">cancel</a></div>
		</div>
<table class="table table-striped">
		<tr>
			<td>
				<label>name</label>
			</td>
			<td>
				<input type="text" name="shippingmethod[name]" value="<?php echo $shippingMethod->name;?>">
				<input type="hidden" name="updated_at" value="" required>
			</td>
		</tr>
		<tr>
			<td>
				<label>amount</label>
			</td>
			<td>
				<input type="text" name="shippingmethod[amount]" value="<?php echo $shippingMethod->amount;?>">
			</td>
		</tr>
		<tr>
			<td>
				<label>status</label>
			</td>
			<td>
				<select name="shippingmethod[status]" >
				<?php foreach($shippingMethod->getResource()->getStatusOptions() as $key => $value): ?>
				<?php $selected = ($key == $shippingMethod->getStatus()) ? 'selected' : ''; ?>
				<option value="<?php echo $key; ?>" <?php echo $selected ;?>> <?php echo $value;?>
				 </option>
				<?php endforeach; ?>
			</select>
			</td>
		</tr>
	</table>
</form>
</body>
</html>