<?php  

$shippingMethod = $this->getRow();
$attributes = $this->getAttributes();

?>
<form action="<?php echo $this->getUrl('save','shippingmethod')?>" method="post" id="shippingmethod-form">
<div class="d-flex align-items-center justify-content-sm-between">
		<p class="fw-bolder fs-4">Edit Shippingmethod</p>
			<button class="btn btn-dark ms-5" type="button" onclick="ajax.setUrl('<?php echo $this->getUrl('save') ?>').setForm('shippingmethod-form').call();">Save</button>
			<button class="btn btn-dark ms-5" type="button" onclick="ajax.setUrl('<?php echo $this->getUrl('grid') ?>').call();">Cancel</button>
		</div>
<table class="table table-striped">
		<tr>
			<td>
				<label>name</label>
			</td>
			<td>
				<input type="text" name="shippingmethod[name]" value="<?php echo $shippingMethod->name;?>">
				<input type="hidden" name="updated_at" value="" required>
			</td>
		</tr>
		<tr>
			<td>
				<label>amount</label>
			</td>
			<td>
				<input type="text" name="shippingmethod[amount]" value="<?php echo $shippingMethod->amount;?>">
			</td>
		</tr>
		<tr>
			<td>
				<label>status</label>
			</td>
			<td>
				<select name="shippingmethod[status]" >
				<?php foreach($shippingMethod->getResource()->getStatusOptions() as $key => $value): ?>
				<?php $selected = ($key == $shippingMethod->getStatus()) ? 'selected' : ''; ?>
				<option value="<?php echo $key; ?>" <?php echo $selected ;?>> <?php echo $value;?>
				 </option>
				<?php endforeach; ?>
			</select>
			</td>
		</tr>
		<?php foreach($attributes as $key => $attribute): ?>
		<tr>
			<td><?php echo $attribute->name ;?></td>
			<td>
				<?php $this->getLayout()->createBlock('Core_Eav_Attribute_InputType')->setAttribute($attribute)->setRow($shippingMethod)->render(); ?>
			</td>
		</tr>
	<?php endforeach; ?>
	</table>
</form>
</body>
</html>