<?php  
$rows = $this->getCollection();
// print_r($this->getColumnValue($row, $key));
// echo "<pre>";
?>
<form id="grid-form" method="post">
<div class="d-flex align-items-center justify-content-sm-between">
	<p class="fw-bolder fs-4"><?php echo $this->getTitle(); ?></p>
	
	<div class="m-2 mx-2">
		<?php foreach($this->getButtons() as $key => $button):  ?>
		<a class="btn btn-dark pull-right" onclick="ajax.setUrl('<?php echo $button['url'] ?>').call()"><?php echo $button['title']; ?></a>
		<?php endforeach; ?>
	</div>
	
</div>
<table class="table table-striped text-center ">
		<tr>
			<?php foreach($this->getColumns() as $key => $column):  ?>
			<th><?php echo $column['title']; ?></th>
			<?php endforeach; ?>
			<?php foreach($this->getActions() as $key => $action):  ?>
			<th><?php echo $action['title']; ?></th>
			<?php endforeach; ?>
		</tr>
		<?php if (!$rows):?>
		<tr>
			<td colspan="16">No record found</td>
		</tr>
		<?php else: ?>
		<?php foreach($rows->getData() as $row):?>
			<tr>
				<?php foreach($this->getColumns() as $key => $column):  ?>
				<td><?php echo $this->getColumnValue($row, $key);?></td>
				<?php endforeach; ?>

				<?php foreach($this->getActions() as $key => $action): ?>
				<td>
					<input name="add" value="<?php echo $action['title']; ?>" type="button" onclick="ajax.setUrl('<?php $method = $action['method']; echo $this->$method($row, $key, $action['primaryKey']);?>').call()">
				</td>
				<?php endforeach; ?>
			</tr>
		<?php endforeach; ?>
		<?php endif; ?>
	</table>
</form>
